# Generated by Django 3.1 on 2020-10-14 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordekeep', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='passwordnum',
            field=models.IntegerField(),
        ),
    ]
