# Generated by Django 3.1 on 2020-10-21 14:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recordekeep', '0002_auto_20201014_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='insertdate',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='customers',
            name='dob',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
