# Generated by Django 3.1 on 2020-10-22 07:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recordekeep', '0004_auto_20201022_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='messege',
            name='email',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='recordekeep.customers'),
            preserve_default=False,
        ),
    ]
