# Generated by Django 3.1 on 2020-10-23 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordekeep', '0005_messege_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.RemoveField(
            model_name='messege',
            name='email',
        ),
    ]
